# Generated by Django 5.2.4 on 2026-02-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='audience',
            field=models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni'), ('all', 'All')], default='all', max_length=10),
        ),
    ]
