# Generated by Django 5.2.4 on 2026-02-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_skills_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
