# Generated by Django 5.2.4 on 2026-02-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('dm', 'Direct Message'), ('group', 'Group')], default='dm', max_length=20),
        ),
        migrations.AddField(
            model_name='chat',
            name='group_context',
            field=models.CharField(blank=True, help_text="Unique key for auto-groups (e.g., 'batch_2024')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
